### ISSUE TITLE
Incorrectly typed constant to get subcommand options

### ISSUE THREAD

**Issue by buttermiilk** [OreOreki/yor.ts#3]
Upon using any `CommandContext`'s method to get subcommand options, for example:
```js
const string = ctx.getStringOption("string");
ctx.reply({ content: string });
```
This currently returns a `DiscordAPIError: Cannot send an empty message`. 

I believe the issue lies on line 232 of [src/Contexts/CommandContext](https://github.com/OreOreki/yor.ts/blob/main/src/structures/Contexts/CommandContext.ts#L232):
```js
const options = this.raw.data.options;
```
This returns an `Array` which contains the actual expected `options[]` of this method, causing the output to be `null`:
```js
// Structure of this.raw.data.options
options: [{ name, options: [], type }]
// Expected structure
options: [{ name, value, type }]
// This is currently finding the subcommand
option = options.find((option) => option.name === name);
```

I temporarily patched the issue by editing that line:
```js
const options = this.raw.data.options[0].options;
```

**Comment by OreOreki** [comment]
Hii @buttermiilk, the `<CommandContext>.getStringOption()` takes in 3 parameters if you're trying to get an option that is in a subcommand the correct way to get it would be 

`context.getStringOption("string" 1, true);`

1. The first parameter is option name
2. The second parameter is option index, 
     0 for base command option
     1 for subcommand
     2 for subcommand group

**Comment by buttermiilk** [comment]
Ah, thanks for clarifying that! I suppose I'm too focused on the Discord.js equivalent implementation 🤣
